In [14]:
import pandas as pd
#from sklearn.preprocessing import MinMaxScaler
from pandas import datetime
import tensorflow as tf

In [15]:
train_df = pd.read_csv('editedab.csv',index_col=0)
train_df.head()

           DATE  TMR  GRASS  WATER  BATH  MILK
COWid
cow01  01-01-19  6.8   17.6   28.6     3  18.0
cow01  02-01-19  5.6   13.9   15.3     2  16.8
cow01  03-01-19  7.1   17.9   24.2     1  14.5
cow01  04-01-19  6.6   14.5   22.3     0  14.3
cow01  05-01-19  7.4   17.3   29.0     3  17.6

In [16]:
train_df.describe()

              TMR       GRASS       WATER        BATH        MILK
count  240.000000  240.000000  240.000000  240.000000  240.000000
mean     6.486250   15.795833   23.039167    1.833333   17.907083
std      0.610661    1.567659    4.069466    0.890050    2.276934
min      5.500000   13.000000   15.100000    0.000000   14.000000
25%      5.900000   14.400000   20.000000    1.000000   15.875000
50%      6.500000   15.900000   23.200000    2.000000   18.000000
75%      7.000000   17.100000   26.200000    3.000000   20.100000
max      8.600000   18.400000   30.000000    3.000000   22.000000

In [17]:
X = train_df.iloc[:,1:5].values
y = train_df.iloc[:,len(train_df.iloc[0])-1].values

In [18]:
print(X)
print(y)

[[ 6.8 17.6 28.6  3. ]
 [ 5.6 13.9 15.3  2. ]
 [ 7.1 17.9 24.2  1. ]
 [ 6.6 14.5 22.3  0. ]
 [ 7.4 17.3 29.   3. ]
 [ 6.1 17.3 20.4  2. ]
 [ 5.7 17.6 28.6  0. ]
 [ 7.3 16.1 21.1  0. ]
 [ 7.  14.1 21.1  3. ]
 [ 5.6 13.7 22.9  3. ]
 [ 6.7 14.1 21.4  1. ]
 [ 7.1 13.8 24.   1. ]
 [ 6.1 17.1 23.8  1. ]
 [ 6.7 18.1 29.1  3. ]
 [ 6.9 14.2 24.1  0. ]
 [ 7.3 18.  25.4  1. ]
 [ 7.1 15.8 29.5  1. ]
 [ 5.8 18.4 25.   0. ]
 [ 7.3 18.4 22.2  2. ]
 [ 6.1 17.  27.2  3. ]
 [ 5.7 17.7 21.4  2. ]
 [ 6.4 15.9 29.1  0. ]
 [ 6.1 13.  23.6  3. ]
 [ 6.3 18.4 16.4  1. ]
 [ 5.9 17.9 19.7  2. ]
 [ 7.1 16.9 15.1  2. ]
 [ 6.8 14.5 27.1  3. ]
 [ 5.9 15.1 23.4  1. ]
 [ 6.2 17.3 20.9  1. ]
 [ 5.6 13.3 29.   0. ]
 [ 7.4 15.6 23.4  3. ]
 [ 5.8 13.1 27.9  2. ]
 [ 6.8 15.2 21.2  0. ]
 [ 5.9 16.3 18.1  1. ]
 [ 6.2 15.6 20.4  1. ]
 [ 6.7 16.5 15.9  0. ]
 [ 6.8 18.3 27.6  3. ]
 [ 6.3 14.8 21.5  1. ]
 [ 6.9 13.7 21.7  1. ]
 [ 6.6 17.3 15.3  2. ]
 [ 6.6 15.  16.8  1. ]
 [ 6.6 15.6 19.7  0. ]
 [ 5.6 17.1 19.5  0. ]
 [ 7.  16.1 25.   1. ]
 [ 6.2 13.6 26.2  1. ]
 [ 6.  15.6 29.5  0. ]
 [ 6.4 14.3 27.6  3. ]
 [ 5.8 13.7 19.1  1. ]
 [ 5.9 16.  24.3  2. ]
 [ 5.9 16.1 26.4  1. ]
 [ 5.6 14.8 28.7  1. ]
 [ 6.3 18.3 22.4  1. ]
 [ 7.4 14.4 19.   1. ]
 [ 7.3 14.1 26.3  1. ]
 [ 6.  13.8 25.5  2. ]
 [ 7.1 15.2 15.8  2. ]
 [ 6.2 14.2 21.8  2. ]
 [ 6.8 17.4 16.7  2. ]
 [ 5.8 16.1 26.9  2. ]
 [ 5.9 16.8 20.4  2. ]
 [ 6.5 13.2 15.8  3. ]
 [ 6.9 14.4 15.8  3. ]
 [ 6.2 16.5 26.4  2. ]
 [ 6.9 17.9 22.5  1. ]
 [ 7.2 18.1 29.6  2. ]
 [ 5.5 15.7 23.8  2. ]
 [ 6.3 14.3 28.2  1. ]
 [ 6.3 17.  21.5  2. ]
 [ 6.9 17.9 24.9  1. ]
 [ 6.1 16.8 29.7  1. ]
 [ 6.1 14.1 20.7  1. ]
 [ 7.4 16.6 26.8  1. ]
 [ 6.1 16.7 19.4  3. ]
 [ 6.  17.6 15.6  2. ]
 [ 5.8 16.4 24.3  2. ]
 [ 7.  17.3 23.7  3. ]
 [ 5.6 14.5 24.8  2. ]
 [ 7.4 14.7 17.3  1. ]
 [ 6.2 13.4 30.   2. ]
 [ 5.9 14.4 23.2  3. ]
 [ 6.5 13.2 29.   2. ]
 [ 7.5 15.6 25.4  1. ]
 [ 7.4 14.2 25.8  1. ]
 [ 5.7 13.  24.8  2. ]
 [ 7.4 16.9 19.2  2. ]
 [ 7.5 18.4 19.1  2. ]
 [ 5.7 16.3 25.3  3. ]
 [ 5.5 16.4 17.2  2. ]
 [ 6.3 13.1 26.2  3. ]
 [ 5.8 16.9 29.7  2. ]
 [ 6.4 16.3 28.5  2. ]
 [ 6.1 17.6 16.1  3. ]
 [ 7.3 14.6 26.6  1. ]
 [ 5.9 15.  25.9  1. ]
 [ 6.  17.1 23.2  1. ]
 [ 7.  16.2 22.3  2. ]
 [ 7.3 17.  26.2  3. ]
 [ 7.5 17.6 15.3  1. ]
 [ 7.3 14.7 18.7  1. ]
 [ 7.1 14.7 28.   1. ]
 [ 7.2 13.9 25.7  3. ]
 [ 5.7 14.9 22.   1. ]
 [ 6.5 17.1 19.2  2. ]
 [ 6.3 14.1 21.3  3. ]
 [ 5.7 13.8 22.3  0. ]
 [ 5.5 16.5 21.8  2. ]
 [ 7.1 17.3 22.1  1. ]
 [ 5.9 14.4 20.   2. ]
 [ 7.  18.  25.6  1. ]
 [ 7.  15.1 26.2  1. ]
 [ 6.5 14.4 26.7  1. ]
 [ 7.1 17.5 25.5  2. ]
 [ 6.5 13.3 23.2  2. ]
 [ 5.6 17.6 28.9  1. ]
 [ 6.2 14.1 20.2  2. ]
 [ 6.8 16.6 25.9  3. ]
 [ 6.4 17.4 29.3  2. ]
 [ 6.5 15.9 18.3  2. ]
 [ 6.7 17.  20.   2. ]
 [ 6.5 18.  15.2  3. ]
 [ 8.6 18.2 28.1  3. ]
 [ 6.6 16.7 23.6  2. ]
 [ 7.4 14.9 17.1  3. ]
 [ 7.1 13.1 26.4  3. ]
 [ 5.9 16.2 21.7  3. ]
 [ 5.8 13.1 26.5  3. ]
 [ 6.1 13.2 27.9  2. ]
 [ 7.  17.1 15.5  2. ]
 [ 5.8 14.2 24.3  3. ]
 [ 6.3 15.8 20.5  2. ]
 [ 7.2 13.8 16.7  1. ]
 [ 6.8 16.4 22.3  2. ]
 [ 5.6 13.3 20.   1. ]
 [ 7.5 14.5 27.2  3. ]
 [ 7.  15.  27.4  1. ]
 [ 7.2 13.3 22.7  2. ]
 [ 6.7 17.9 22.2  3. ]
 [ 7.1 15.8 21.6  2. ]
 [ 7.2 16.3 27.3  2. ]
 [ 7.5 17.4 22.9  1. ]
 [ 5.6 14.2 22.5  0. ]
 [ 6.3 16.6 22.3  3. ]
 [ 5.7 14.  19.   2. ]
 [ 6.9 15.5 27.8  3. ]
 [ 7.  16.7 25.4  2. ]
 [ 6.6 13.5 26.3  0. ]
 [ 5.6 14.1 29.8  3. ]
 [ 6.6 14.5 23.   3. ]
 [ 5.8 15.3 24.2  2. ]
 [ 6.5 13.6 23.9  3. ]
 [ 7.4 16.2 15.5  1. ]
 [ 5.6 15.1 23.2  2. ]
 [ 6.6 15.3 15.2  3. ]
 [ 6.6 17.1 16.9  1. ]
 [ 6.5 18.2 20.3  2. ]
 [ 7.1 16.3 18.2  2. ]
 [ 6.3 17.8 21.4  2. ]
 [ 5.9 16.6 23.3  3. ]
 [ 6.1 13.4 26.1  1. ]
 [ 6.2 15.3 23.3  2. ]
 [ 5.8 13.7 16.6  2. ]
 [ 6.7 14.7 21.9  2. ]
 [ 6.5 16.9 23.1  1. ]
 [ 5.8 18.  17.1  2. ]
 [ 6.2 17.9 28.1  3. ]
 [ 5.6 15.  17.7  2. ]
 [ 7.1 15.3 15.7  1. ]
 [ 6.6 18.1 25.9  3. ]
 [ 7.5 15.  17.3  1. ]
 [ 7.  18.4 18.2  2. ]
 [ 6.3 16.2 29.7  2. ]
 [ 6.8 17.8 21.7  3. ]
 [ 7.3 16.4 22.1  3. ]
 [ 7.1 14.2 22.6  2. ]
 [ 7.4 15.4 23.7  2. ]
 [ 7.2 16.7 19.   1. ]
 [ 6.  17.  23.3  3. ]
 [ 5.7 17.8 16.9  2. ]
 [ 5.9 16.4 23.8  2. ]
 [ 7.1 13.9 25.   2. ]
 [ 5.7 14.5 23.8  1. ]
 [ 5.9 14.7 21.2  1. ]
 [ 7.  15.3 18.5  2. ]
 [ 5.8 17.6 26.1  2. ]
 [ 5.7 14.8 19.8  3. ]
 [ 7.3 17.8 19.9  0. ]
 [ 7.3 18.2 28.6  1. ]
 [ 7.3 16.1 29.3  2. ]
 [ 6.6 14.8 20.3  1. ]
 [ 7.1 15.5 25.8  2. ]
 [ 5.9 18.2 22.5  2. ]
 [ 6.7 13.6 27.1  1. ]
 [ 7.1 17.6 29.9  3. ]
 [ 7.  16.4 19.7  1. ]
 [ 7.  17.9 24.3  3. ]
 [ 6.9 18.  18.2  1. ]
 [ 6.  14.1 22.8  1. ]
 [ 6.7 17.2 23.3  2. ]
 [ 6.1 15.1 29.2  2. ]
 [ 6.9 14.1 23.2  3. ]
 [ 5.6 13.4 26.5  2. ]
 [ 6.1 14.  21.6  2. ]
 [ 5.9 14.6 23.5  3. ]
 [ 6.7 13.6 24.2  1. ]
 [ 5.6 16.6 18.4  1. ]
 [ 7.4 14.2 25.   2. ]
 [ 5.8 16.  21.5  2. ]
 [ 5.9 17.8 29.2  2. ]
 [ 6.1 13.7 16.4  2. ]
 [ 5.5 16.4 22.7  3. ]
 [ 6.8 15.5 17.4  3. ]
 [ 7.3 14.7 16.9  2. ]
 [ 6.9 14.3 29.1  3. ]
 [ 5.9 15.4 24.3  2. ]
 [ 6.2 18.3 16.2  2. ]
 [ 5.6 16.9 21.3  2. ]
 [ 5.7 15.3 22.4  3. ]
 [ 6.8 14.4 29.8  3. ]
 [ 6.5 13.5 18.3  2. ]
 [ 6.8 16.6 20.6  2. ]
 [ 6.1 17.6 22.8  2. ]
 [ 7.3 18.4 25.8  3. ]
 [ 6.5 14.7 26.5  1. ]
 [ 5.6 18.3 19.   0. ]
 [ 5.7 16.4 24.   2. ]
 [ 7.3 15.1 21.3  3. ]
 [ 6.  16.3 19.1  2. ]
 [ 7.2 16.9 24.2  3. ]
 [ 6.  16.1 28.6  2. ]
 [ 6.6 15.6 25.8  1. ]
 [ 5.8 14.1 21.6  1. ]
 [ 5.8 17.4 29.   2. ]
 [ 6.4 17.6 19.1  3. ]
 [ 7.2 16.  28.2  3. ]
 [ 6.9 15.9 25.4  2. ]
 [ 6.1 16.5 29.5  2. ]
 [ 5.7 14.1 22.6  3. ]
 [ 7.  15.2 26.8  2. ]
 [ 6.8 17.9 26.   3. ]
 [ 6.4 15.2 29.   2. ]]
[18.  16.8 14.5 14.3 17.6 16.3 14.  14.3 16.5 17.3 15.8 14.2 15.5 17.5
 14.1 14.6 14.4 14.3 17.  18.  16.2 14.2 17.5 14.5 15.9 15.9 17.8 14.2
 15.8 14.  17.3 16.  14.8 16.3 16.8 16.5 17.9 15.  15.8 16.9 17.  14.9
 17.  16.7 14.5 16.4 17.3 14.2 15.5 14.9 15.6 14.6 14.7 15.3 17.3 16.2
 16.9 16.6 16.2 15.4 17.4 17.3 16.6 15.  15.6 16.3 15.3 16.9 15.3 15.7
 15.1 15.1 17.2 14.5 15.6 17.2 15.5 14.4 15.  17.7 16.  15.  14.3 16.2
 15.7 15.5 16.9 16.9 17.5 14.8 15.2 17.1 14.4 15.7 16.1 16.5 17.1 16.5
 16.4 15.3 17.4 15.4 16.4 17.  14.6 16.9 15.5 15.2 15.6 15.7 14.8 15.8
 16.1 16.1 14.7 17.1 16.8 16.9 14.8 16.7 22.  18.9 19.9 19.3 20.7 20.7
 19.8 19.7 21.3 20.1 18.5 19.2 18.6 21.3 18.9 21.1 21.4 20.  21.  18.1
 18.2 21.2 19.3 21.4 20.3 18.  21.1 21.1 18.7 21.3 18.4 20.6 21.2 18.9
 19.  19.  20.6 20.7 18.3 20.1 20.3 20.8 18.6 20.2 20.4 18.9 19.  20.8
 20.1 18.9 20.6 20.7 20.8 19.5 21.1 18.1 21.  20.4 20.3 20.6 18.7 19.7
 20.1 20.2 20.8 18.3 18.8 20.2 18.  20.9 19.  18.9 21.5 18.9 21.  18.4
 18.6 20.7 19.8 21.1 19.5 20.  21.  18.2 18.8 20.  19.1 18.1 19.9 20.5
 21.1 18.8 21.4 20.9 19.5 19.9 21.4 21.  20.5 19.1 20.7 20.4 18.8 18.1
 20.2 20.7 19.6 21.  20.4 18.5 18.  18.4 20.9 21.4 18.2 20.  20.1 20.2
 21.5 20.5]

In [19]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [20]:
# Import `StandardScaler` from `sklearn.preprocessing`
#from sklearn.preprocessing import StandardScaler

# Define the scaler 
#scaler = StandardScaler().fit(X_train)

# Scale the train set
#X_train = scaler.transform(X_train)

# Scale the test set
#X_test = scaler.transform(X_test)

In [21]:
print(X_train)
print('\n')
print(X_test)

[[ 6.5 14.4 26.7  1. ]
 [ 6.4 15.2 29.   2. ]
 [ 6.9 17.9 22.5  1. ]
 [ 6.6 17.1 16.9  1. ]
 [ 7.2 16.  28.2  3. ]
 [ 7.5 17.4 22.9  1. ]
 [ 7.3 17.  26.2  3. ]
 [ 5.9 16.3 18.1  1. ]
 [ 5.8 17.4 29.   2. ]
 [ 6.1 13.4 26.1  1. ]
 [ 6.4 17.4 29.3  2. ]
 [ 7.5 15.  17.3  1. ]
 [ 7.  17.3 23.7  3. ]
 [ 5.6 16.9 21.3  2. ]
 [ 6.4 16.3 28.5  2. ]
 [ 5.8 14.1 21.6  1. ]
 [ 6.1 14.  21.6  2. ]
 [ 7.1 16.3 18.2  2. ]
 [ 7.1 15.8 29.5  1. ]
 [ 6.5 13.5 18.3  2. ]
 [ 6.3 15.8 20.5  2. ]
 [ 6.  17.6 15.6  2. ]
 [ 7.4 17.3 29.   3. ]
 [ 5.9 14.4 20.   2. ]
 [ 6.9 14.4 15.8  3. ]
 [ 6.8 15.5 17.4  3. ]
 [ 7.4 14.4 19.   1. ]
 [ 6.3 14.3 28.2  1. ]
 [ 6.8 14.5 27.1  3. ]
 [ 6.  17.  23.3  3. ]
 [ 6.5 16.9 23.1  1. ]
 [ 5.9 15.4 24.3  2. ]
 [ 6.6 15.  16.8  1. ]
 [ 6.7 18.1 29.1  3. ]
 [ 6.6 14.5 22.3  0. ]
 [ 6.  16.3 19.1  2. ]
 [ 5.9 17.9 19.7  2. ]
 [ 7.4 15.6 23.4  3. ]
 [ 6.2 18.3 16.2  2. ]
 [ 6.5 13.2 15.8  3. ]
 [ 6.2 14.2 21.8  2. ]
 [ 7.2 13.8 16.7  1. ]
 [ 6.7 17.9 22.2  3. ]
 [ 6.1 17.  27.2  3. ]
 [ 5.9 16.4 23.8  2. ]
 [ 6.7 14.7 21.9  2. ]
 [ 6.  13.8 25.5  2. ]
 [ 6.7 13.6 27.1  1. ]
 [ 6.5 13.2 29.   2. ]
 [ 6.3 18.3 22.4  1. ]
 [ 6.8 17.8 21.7  3. ]
 [ 5.9 14.7 21.2  1. ]
 [ 5.9 16.2 21.7  3. ]
 [ 5.7 16.3 25.3  3. ]
 [ 6.1 13.2 27.9  2. ]
 [ 7.2 13.3 22.7  2. ]
 [ 7.  18.4 18.2  2. ]
 [ 7.1 13.1 26.4  3. ]
 [ 6.6 15.6 19.7  0. ]
 [ 6.9 14.2 24.1  0. ]
 [ 5.9 15.1 23.4  1. ]
 [ 5.6 14.8 28.7  1. ]
 [ 6.8 14.4 29.8  3. ]
 [ 5.7 17.7 21.4  2. ]
 [ 6.2 15.3 23.3  2. ]
 [ 6.4 14.3 27.6  3. ]
 [ 6.6 14.8 20.3  1. ]
 [ 6.1 16.5 29.5  2. ]
 [ 7.2 16.3 27.3  2. ]
 [ 5.5 16.4 22.7  3. ]
 [ 6.2 16.5 26.4  2. ]
 [ 5.8 16.  21.5  2. ]
 [ 7.1 17.9 24.2  1. ]
 [ 5.9 16.8 20.4  2. ]
 [ 5.6 14.1 29.8  3. ]
 [ 5.6 18.3 19.   0. ]
 [ 7.  16.1 25.   1. ]
 [ 7.3 16.1 29.3  2. ]
 [ 6.7 14.1 21.4  1. ]
 [ 7.1 15.8 21.6  2. ]
 [ 7.1 15.5 25.8  2. ]
 [ 6.5 13.3 23.2  2. ]
 [ 7.1 14.2 22.6  2. ]
 [ 7.3 14.7 18.7  1. ]
 [ 7.4 16.2 15.5  1. ]
 [ 5.9 15.  25.9  1. ]
 [ 5.8 13.7 16.6  2. ]
 [ 6.6 15.6 25.8  1. ]
 [ 5.6 17.6 28.9  1. ]
 [ 6.8 17.6 28.6  3. ]
 [ 6.  17.1 23.2  1. ]
 [ 7.  16.2 22.3  2. ]
 [ 6.1 16.8 29.7  1. ]
 [ 5.9 16.1 26.4  1. ]
 [ 5.9 16.  24.3  2. ]
 [ 7.5 18.4 19.1  2. ]
 [ 7.  15.2 26.8  2. ]
 [ 6.3 16.6 22.3  3. ]
 [ 6.3 18.4 16.4  1. ]
 [ 6.9 15.5 27.8  3. ]
 [ 6.2 13.4 30.   2. ]
 [ 7.2 13.9 25.7  3. ]
 [ 6.8 16.4 22.3  2. ]
 [ 7.4 14.2 25.   2. ]
 [ 6.8 17.9 26.   3. ]
 [ 5.7 17.6 28.6  0. ]
 [ 6.9 17.9 24.9  1. ]
 [ 7.4 16.9 19.2  2. ]
 [ 6.6 16.7 23.6  2. ]
 [ 5.7 16.4 24.   2. ]
 [ 5.7 14.5 23.8  1. ]
 [ 6.7 13.6 24.2  1. ]
 [ 6.1 15.1 29.2  2. ]
 [ 7.  15.3 18.5  2. ]
 [ 6.1 17.6 16.1  3. ]
 [ 5.6 16.6 18.4  1. ]
 [ 7.1 13.8 24.   1. ]
 [ 6.5 18.  15.2  3. ]
 [ 6.5 17.1 19.2  2. ]
 [ 6.7 16.5 15.9  0. ]
 [ 6.8 17.4 16.7  2. ]
 [ 5.5 15.7 23.8  2. ]
 [ 5.6 13.9 15.3  2. ]
 [ 8.6 18.2 28.1  3. ]
 [ 5.9 18.2 22.5  2. ]
 [ 5.6 17.1 19.5  0. ]
 [ 5.5 16.5 21.8  2. ]
 [ 5.6 13.3 20.   1. ]
 [ 5.9 17.8 29.2  2. ]
 [ 5.8 18.4 25.   0. ]
 [ 6.9 13.7 21.7  1. ]
 [ 7.5 14.5 27.2  3. ]
 [ 7.3 14.1 26.3  1. ]
 [ 6.2 17.9 28.1  3. ]
 [ 7.3 18.2 28.6  1. ]
 [ 5.8 14.2 24.3  3. ]
 [ 6.2 15.6 20.4  1. ]
 [ 6.2 17.3 20.9  1. ]
 [ 5.8 17.6 26.1  2. ]
 [ 6.2 14.1 20.2  2. ]
 [ 5.8 18.  17.1  2. ]
 [ 5.6 15.1 23.2  2. ]
 [ 5.8 13.1 27.9  2. ]
 [ 6.  14.1 22.8  1. ]
 [ 7.  17.1 15.5  2. ]
 [ 7.3 17.8 19.9  0. ]
 [ 6.9 14.3 29.1  3. ]
 [ 6.5 14.7 26.5  1. ]
 [ 6.8 15.2 21.2  0. ]
 [ 6.6 18.1 25.9  3. ]
 [ 5.7 14.  19.   2. ]
 [ 5.6 13.4 26.5  2. ]
 [ 6.6 14.5 23.   3. ]
 [ 5.6 13.3 29.   0. ]
 [ 5.7 17.8 16.9  2. ]
 [ 7.1 14.7 28.   1. ]
 [ 7.4 14.2 25.8  1. ]
 [ 5.7 14.1 22.6  3. ]
 [ 7.2 16.7 19.   1. ]
 [ 5.9 14.4 23.2  3. ]
 [ 6.7 17.2 23.3  2. ]
 [ 6.1 13.7 16.4  2. ]
 [ 6.8 16.6 25.9  3. ]
 [ 5.8 15.3 24.2  2. ]
 [ 6.4 17.6 19.1  3. ]
 [ 6.1 16.7 19.4  3. ]
 [ 7.4 14.7 17.3  1. ]
 [ 7.1 16.9 15.1  2. ]
 [ 5.6 15.  17.7  2. ]
 [ 7.5 15.6 25.4  1. ]
 [ 7.3 15.1 21.3  3. ]
 [ 7.4 15.4 23.7  2. ]
 [ 6.  16.1 28.6  2. ]
 [ 6.6 17.3 15.3  2. ]
 [ 7.  16.4 19.7  1. ]
 [ 5.8 16.1 26.9  2. ]
 [ 5.6 14.2 22.5  0. ]
 [ 6.3 13.1 26.2  3. ]
 [ 5.7 15.3 22.4  3. ]
 [ 6.1 14.1 20.7  1. ]
 [ 5.5 16.4 17.2  2. ]
 [ 6.8 18.3 27.6  3. ]
 [ 6.4 15.9 29.1  0. ]
 [ 7.3 14.7 16.9  2. ]
 [ 5.6 13.7 22.9  3. ]
 [ 6.3 14.1 21.3  3. ]
 [ 6.9 18.  18.2  1. ]
 [ 6.3 17.  21.5  2. ]
 [ 7.1 17.6 29.9  3. ]
 [ 6.5 15.9 18.3  2. ]
 [ 5.8 13.7 19.1  1. ]
 [ 7.3 16.4 22.1  3. ]]


[[ 7.  15.1 26.2  1. ]
 [ 7.4 16.6 26.8  1. ]
 [ 6.3 14.8 21.5  1. ]
 [ 5.8 16.4 24.3  2. ]
 [ 7.  18.  25.6  1. ]
 [ 7.2 16.9 24.2  3. ]
 [ 6.3 17.8 21.4  2. ]
 [ 6.1 17.6 22.8  2. ]
 [ 6.6 15.3 15.2  3. ]
 [ 7.  17.9 24.3  3. ]
 [ 5.6 14.5 24.8  2. ]
 [ 5.9 14.6 23.5  3. ]
 [ 5.7 13.  24.8  2. ]
 [ 5.9 16.6 23.3  3. ]
 [ 6.9 15.9 25.4  2. ]
 [ 7.  15.  27.4  1. ]
 [ 5.7 14.8 19.8  3. ]
 [ 7.1 17.5 25.5  2. ]
 [ 7.3 18.4 25.8  3. ]
 [ 7.  14.1 21.1  3. ]
 [ 5.7 14.9 22.   1. ]
 [ 7.1 13.9 25.   2. ]
 [ 5.8 16.9 29.7  2. ]
 [ 7.4 14.9 17.1  3. ]
 [ 6.1 17.3 20.4  2. ]
 [ 6.1 13.  23.6  3. ]
 [ 6.9 14.1 23.2  3. ]
 [ 7.5 17.6 15.3  1. ]
 [ 6.1 17.1 23.8  1. ]
 [ 7.1 15.3 15.7  1. ]
 [ 7.1 15.2 15.8  2. ]
 [ 6.2 13.6 26.2  1. ]
 [ 6.5 13.6 23.9  3. ]
 [ 5.8 13.1 26.5  3. ]
 [ 7.  16.7 25.4  2. ]
 [ 6.7 17.  20.   2. ]
 [ 6.6 13.5 26.3  0. ]
 [ 6.3 16.2 29.7  2. ]
 [ 7.2 18.1 29.6  2. ]
 [ 7.3 14.6 26.6  1. ]
 [ 6.5 18.2 20.3  2. ]
 [ 6.  15.6 29.5  0. ]
 [ 6.8 16.6 20.6  2. ]
 [ 7.3 18.4 22.2  2. ]
 [ 7.1 17.3 22.1  1. ]
 [ 7.3 18.  25.4  1. ]
 [ 5.7 13.8 22.3  0. ]
 [ 7.3 16.1 21.1  0. ]]

In [22]:

# TensorFlow is a Python library for fast numerical computing created and released by Google. 
# can be used to create Deep Learning models directly.
# Tensors are the basic data structure in TensorFlow which store data
# in any number of dimensions, similar to multi dimensional arrays in NumPy.
# Keras is an Open Source Neural Network library written in Python 
# that runs on top of Tensorflow
# Sequential:-The layers can be defined and passed to the Sequential as an array:
# A dense layer is just a regular layer of neurons in a neural network. 
# Each neuron recieves input from all the neurons in the previous layer, thus densely connected


import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [25]:
# We can now add layers to our model.
# We will be creating fully connected layers using model.add().
# The first call creates two layers, 
# while subsequent calls add one layer each.
# We need to tell each layer what its output will be,
# which is the number of neurons it will output.
# We also need to specify the activation of the layers.
# In this case, we use the relu activation function.


# Build our model
# Notice that the final layer outputs one value. 
# That is because we are predicting a continuous variable. 
# For the same reason, we do not specify an activation.

model = Sequential()
model.add(Dense(50, input_dim=4, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(1))

# Next, we need to compile our model.
# We do this by specifying our loss function and our optimizer 
# The Adam optimization algorithm is an extension to stochastic gradient descent 
# to update network weights iterative based in training data.
# the name Adam is derived from adaptive moment estimation.

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [26]:
# We will separate our predictors into X, and our target into Y.
# We will train our model by passing in our training dataset. 
# We also need to specify the number of times
# we would like to go over our training data. This is called an epoch.


# Check documentation for model.fit here.

# By setting verbose 0, 1 or 2 you just say how do you want to 'see'
# the training progress for each epoch.

# verbose=0 will show you nothing (silent)

# verbose=1 will show you an animated progress bar like this: progres_bar--------------------

# verbose=2 will just mention the number of epoch like this: epoch 1/50


# Train the model
model.fit(X_train, y_train,epochs=50, batch_size=200, verbose=2)

WARNING:tensorflow:From C:\Users\Lenovo\Anaconda3\envs\Neural Network\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/50
 - 6s - loss: 248.1373 - acc: 0.0000e+00
Epoch 2/50
 - 0s - loss: 210.6747 - acc: 0.0000e+00
Epoch 3/50
 - 0s - loss: 181.1000 - acc: 0.0000e+00
Epoch 4/50
 - 0s - loss: 152.0126 - acc: 0.0000e+00
Epoch 5/50
 - 0s - loss: 124.2701 - acc: 0.0000e+00
Epoch 6/50
 - 0s - loss: 99.1759 - acc: 0.0000e+00
Epoch 7/50
 - 0s - loss: 77.0853 - acc: 0.0000e+00
Epoch 8/50
 - 0s - loss: 57.6283 - acc: 0.0000e+00
Epoch 9/50
 - 0s - loss: 40.8941 - acc: 0.0052
Epoch 10/50
 - 0s - loss: 27.7528 - acc: 0.0104
Epoch 11/50
 - 0s - loss: 18.2393 - acc: 0.0156
Epoch 12/50
 - 0s - loss: 11.9777 - acc: 0.0052
Epoch 13/50
 - 0s - loss: 8.9455 - acc: 0.0052
Epoch 14/50
 - 0s - loss: 8.9833 - acc: 0.0260
Epoch 15/50
 - 0s - loss: 11.4812 - acc: 0.0208
Epoch 16/50
 - 0s - loss: 15.2626 - acc: 0.0208
Epoch 17/50
 - 0s - loss: 19.0163 - acc: 0.0208
Epoch 18/50
 - 0s - loss: 21.7418 - acc: 0.0156
Epoch 19/50
 - 0s - loss: 22.9216 - acc: 0.0104
Epoch 20/50
 - 0s - loss: 22.5324 - acc: 0.0104
Epoch 21/50
 - 0s - loss: 20.9143 - acc: 0.0156
Epoch 22/50
 - 0s - loss: 18.5557 - acc: 0.0156
Epoch 23/50
 - 0s - loss: 15.9084 - acc: 0.0156
Epoch 24/50
 - 0s - loss: 13.3220 - acc: 0.0156
Epoch 25/50
 - 0s - loss: 11.0974 - acc: 0.0156
Epoch 26/50
 - 0s - loss: 9.4321 - acc: 0.0156
Epoch 27/50
 - 0s - loss: 8.4002 - acc: 0.0260
Epoch 28/50
 - 0s - loss: 7.9602 - acc: 0.0156
Epoch 29/50
 - 0s - loss: 7.9989 - acc: 0.0000e+00
Epoch 30/50
 - 0s - loss: 8.3602 - acc: 0.0052
Epoch 31/50
 - 0s - loss: 8.8817 - acc: 0.0052
Epoch 32/50
 - 0s - loss: 9.4150 - acc: 0.0000e+00
Epoch 33/50
 - 0s - loss: 9.8408 - acc: 0.0052
Epoch 34/50
 - 0s - loss: 10.0802 - acc: 0.0052
Epoch 35/50
 - 0s - loss: 10.0982 - acc: 0.0052
Epoch 36/50
 - 0s - loss: 9.8987 - acc: 0.0052
Epoch 37/50
 - 0s - loss: 9.5184 - acc: 0.0052
Epoch 38/50
 - 0s - loss: 9.0160 - acc: 0.0000e+00
Epoch 39/50
 - 0s - loss: 8.4605 - acc: 0.0000e+00
Epoch 40/50
 - 0s - loss: 7.9216 - acc: 0.0052
Epoch 41/50
 - 0s - loss: 7.4583 - acc: 0.0052
Epoch 42/50
 - 0s - loss: 7.1128 - acc: 0.0052
Epoch 43/50
 - 0s - loss: 6.8997 - acc: 0.0104
Epoch 44/50
 - 0s - loss: 6.8171 - acc: 0.0208
Epoch 45/50
 - 0s - loss: 6.8426 - acc: 0.0260
Epoch 46/50
 - 0s - loss: 6.9329 - acc: 0.0260
Epoch 47/50
 - 0s - loss: 7.0444 - acc: 0.0260
Epoch 48/50
 - 0s - loss: 7.1395 - acc: 0.0260
Epoch 49/50
 - 0s - loss: 7.1713 - acc: 0.0156
Epoch 50/50
 - 0s - loss: 7.1114 - acc: 0.0156

In [27]:
y_pred = model.predict(X_test)
print(y_pred)

[[19.32596 ]
 [20.368303]
 [17.340405]
 [19.111515]
 [20.522015]
 [20.227549]
 [19.115808]
 [19.380354]
 [16.339394]
 [20.691702]
 [18.324236]
 [18.334803]
 [17.759361]
 [19.281057]
 [19.700348]
 [19.772207]
 [17.19033 ]
 [20.58368 ]
 [21.532919]
 [17.740414]
 [17.28337 ]
 [18.715042]
 [21.22964 ]
 [17.053507]
 [18.466055]
 [17.740889]
 [18.399729]
 [17.257599]
 [19.104227]
 [16.06357 ]
 [16.361635]
 [18.46419 ]
 [18.263227]
 [18.807257]
 [20.128975]
 [18.431944]
 [18.36363 ]
 [21.157705]
 [22.26855 ]
 [19.413168]
 [19.050192]
 [20.253447]
 [18.463547]
 [20.076033]
 [19.084219]
 [20.582714]
 [16.543146]
 [17.945948]]

In [28]:
diff=y_test-y_pred
print(diff)

[[-3.62596016 -4.22596016 -4.32596016 ... -4.72596016 -4.72596016
  -5.02596016]
 [-4.6683033  -5.2683033  -5.3683033  ... -5.7683033  -5.7683033
  -6.0683033 ]
 [-1.64040451 -2.24040451 -2.34040451 ... -2.74040451 -2.74040451
  -3.04040451]
 ...
 [-4.88271408 -5.48271408 -5.58271408 ... -5.98271408 -5.98271408
  -6.28271408]
 [-0.84314613 -1.44314613 -1.54314613 ... -1.94314613 -1.94314613
  -2.24314613]
 [-2.24594765 -2.84594765 -2.94594765 ... -3.34594765 -3.34594765
  -3.64594765]]

In [29]:
df=pd.DataFrame([y_test, y_pred])  
df 
df1=df.head(25)

In [30]:
from sklearn import metrics 
import numpy as np
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 2.5771627028783164
Mean Squared Error: 9.6974758224922
Root Mean Squared Error: 3.1140770418363446

In [31]:
ynew = model.predict([[[6.8,17.6,28.6,3]]])
print(ynew)

[[21.85637]]

In [32]:
X_test

array([[ 7. , 15.1, 26.2,  1. ],
       [ 7.4, 16.6, 26.8,  1. ],
       [ 6.3, 14.8, 21.5,  1. ],
       [ 5.8, 16.4, 24.3,  2. ],
       [ 7. , 18. , 25.6,  1. ],
       [ 7.2, 16.9, 24.2,  3. ],
       [ 6.3, 17.8, 21.4,  2. ],
       [ 6.1, 17.6, 22.8,  2. ],
       [ 6.6, 15.3, 15.2,  3. ],
       [ 7. , 17.9, 24.3,  3. ],
       [ 5.6, 14.5, 24.8,  2. ],
       [ 5.9, 14.6, 23.5,  3. ],
       [ 5.7, 13. , 24.8,  2. ],
       [ 5.9, 16.6, 23.3,  3. ],
       [ 6.9, 15.9, 25.4,  2. ],
       [ 7. , 15. , 27.4,  1. ],
       [ 5.7, 14.8, 19.8,  3. ],
       [ 7.1, 17.5, 25.5,  2. ],
       [ 7.3, 18.4, 25.8,  3. ],
       [ 7. , 14.1, 21.1,  3. ],
       [ 5.7, 14.9, 22. ,  1. ],
       [ 7.1, 13.9, 25. ,  2. ],
       [ 5.8, 16.9, 29.7,  2. ],
       [ 7.4, 14.9, 17.1,  3. ],
       [ 6.1, 17.3, 20.4,  2. ],
       [ 6.1, 13. , 23.6,  3. ],
       [ 6.9, 14.1, 23.2,  3. ],
       [ 7.5, 17.6, 15.3,  1. ],
       [ 6.1, 17.1, 23.8,  1. ],
       [ 7.1, 15.3, 15.7,  1. ],
       [ 7.1, 15.2, 15.8,  2. ],
       [ 6.2, 13.6, 26.2,  1. ],
       [ 6.5, 13.6, 23.9,  3. ],
       [ 5.8, 13.1, 26.5,  3. ],
       [ 7. , 16.7, 25.4,  2. ],
       [ 6.7, 17. , 20. ,  2. ],
       [ 6.6, 13.5, 26.3,  0. ],
       [ 6.3, 16.2, 29.7,  2. ],
       [ 7.2, 18.1, 29.6,  2. ],
       [ 7.3, 14.6, 26.6,  1. ],
       [ 6.5, 18.2, 20.3,  2. ],
       [ 6. , 15.6, 29.5,  0. ],
       [ 6.8, 16.6, 20.6,  2. ],
       [ 7.3, 18.4, 22.2,  2. ],
       [ 7.1, 17.3, 22.1,  1. ],
       [ 7.3, 18. , 25.4,  1. ],
       [ 5.7, 13.8, 22.3,  0. ],
       [ 7.3, 16.1, 21.1,  0. ]])

In [33]:
y_test

array([15.7, 15.1, 15. , 15.6, 15.6, 21. , 20.6, 20.7, 21.2, 21. , 15.5,
       21. , 16.2, 20.7, 18.2, 18.9, 20.8, 15.8, 20.4, 16.5, 15.4, 20.6,
       14.8, 19.9, 16.3, 17.5, 21.1, 16.5, 15.5, 19. , 16.2, 14.5, 21.3,
       20.7, 20.3, 14.8, 18. , 20.6, 15.6, 14.4, 19. , 16.4, 19.1, 17. ,
       15.5, 14.6, 14.6, 14.3])

In [34]:

from sklearn.metrics import r2_score
accuracy=r2_score(y_test, y_pred)
print(accuracy*100)

-59.261935173382895

In [ ]:
model.evaluate(X_test, y_test)

In [ ]:
df1.plot(kind='bar',figsize=(10,8))
plt.grid(which='major', linestyle='-', linewidth='0.5', color='green')
plt.grid(which='minor', linestyle=':', linewidth='0.5', color='black')
plt.show()